- name: Ansible en Azure
  href: ./index.yml
- name: Información general
  items:
    - name: Acerca de Ansible en Azure
      href: ./ansible-overview.md
- name: Inicios rápidos
  expanded: true
  items:
    - name: Instalación y configuración de Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Creación de una máquina virtual Linux
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutoriales
  items:
    - name: Creación de una máquina virtual Linux completa
      href: /azure/virtual-machines/linux/ansible-create-complete-vm
      maintainContext: true
    - name: Ejecución de un guión de procedimientos en Cloud Shell
      href: ./ansible-run-playbook-in-cloudshell.md
      maintainContext: true
    - name: Administración de inventarios dinámicos
      href: ./ansible-manage-azure-dynamic-inventories.md
      maintainContext: true
- name: Referencia
  items:
    - name: Roles de guión de procedimientos
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: Versiones y características
      href: ./ansible-matrix.md
    - name: Azure Container Instances
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_acs_module.html'
    - name: Azure Functions
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html'
    - name: Equilibradores de carga
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html'
    - name: Máquinas virtuales
      href: 'http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html'
    - name: Todos los módulos de Azure
      href: 'http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure'